(function() {var implementors = {};
implementors["2i_emulator"] = [{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"2i_emulator/struct.Computer.html\" title=\"struct 2i_emulator::Computer\">Computer</a>&lt;'a&gt;",synthetic:false,types:["2i_emulator::Computer"]},];
implementors["emulator"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"emulator/alu/struct.Flags.html\" title=\"struct emulator::alu::Flags\">Flags</a>",synthetic:false,types:["emulator::alu::Flags"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"emulator/bus/struct.Ram.html\" title=\"struct emulator::bus::Ram\">Ram</a>&lt;'a&gt;",synthetic:false,types:["emulator::bus::Ram"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"emulator/bus/struct.IoRegisters.html\" title=\"struct emulator::bus::IoRegisters\">IoRegisters</a>",synthetic:false,types:["emulator::bus::IoRegisters"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"emulator/cpu/struct.Cpu.html\" title=\"struct emulator::cpu::Cpu\">Cpu</a>",synthetic:false,types:["emulator::cpu::Cpu"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"emulator/instruction/struct.Instruction.html\" title=\"struct emulator::instruction::Instruction\">Instruction</a>",synthetic:false,types:["emulator::instruction::Instruction"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
